import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React, {useEffect, useState} from 'react';
import axios from 'axios';
import Image from 'next/image';


export default function Characters() {
    const [characters, setCharacters] = useState<null | CharacterType[]>(null)

    useEffect(() => {
        axios.get('https://rickandmortyapi.com/api/character')
            .then(res => setCharacters(res.data.results))
    }, []);

    return (
        <>
            <Head>
                <title>Characters</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                {characters && characters.map(character => (
                    <div key={character.id}>
                        <div>{character.name}</div>
                        <Image src={character.image}
                               alt={`Picture of ${character.name}`}
                               width={300}
                               height={300}
                        />
                    </div>
                ))}
            </main>
        </>
    );
}

//types
type CharacterType = {
    id: number
    name: string
    image: string
}
