import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React from 'react';
import {useCharacters} from '@/assets/hooks/useCharacters';
import {CharacterCard} from '@/components/CharacterCard/CharacterCard';


export default function Characters() {
    const characters = useCharacters()

    return (
        <>
            <Head>
                <title>Characters</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                {characters && characters.map(character => (
                    <CharacterCard key={character.id} character={character}/>
                ))}
            </main>
        </>
    );
}

